import { Page } from '@playwright/test';
import { waitForVerificationLink } from './mailpit';

/**
 * Zitadel self-registration + Mailpit email-verification driver for the RBAC scenarios
 * (01/04), where a "registration user" (cei-admin, usccb-editor) is NOT seeded by
 * rbac.setup.ts and must create its own account through the real Zitadel login-v2 UI.
 *
 * Self-registration is enabled on the test org (login policy `allowRegister: true`), and
 * Zitadel delivers the verification email to Mailpit (SMTP mailpit:1025) for the
 * `<id>+e2e@litcal.test` address pattern. Cross-org registration lands in ZITADEL_ORG_ID
 * (the org the OIDC client belongs to), the same org rbac.setup.ts seeds into.
 *
 * --- Pinned flow + selectors (login-v2, served at ZITADEL login UI; verified live against
 *     the local docker stack) -------------------------------------------------------------
 *
 *  0. GET {FRONTEND_URL}/auth/login.php  → 302 to Zitadel  → /ui/v2/login/loginname
 *       [data-testid="register-button"]   (button, text "Register new user")
 *
 *  1. click register-button             → /ui/v2/login/register
 *       [data-testid="firstname-text-input"]   (name=firstname, required)
 *       [data-testid="lastname-text-input"]    (name=lastname,  required)
 *       [data-testid="email-text-input"]       (name=email,     required)
 *       [data-testid="password-radio"]         (auth-method selector; choose password)
 *       [data-testid="submit-button"]          ("Continue")
 *
 *  2. submit                            → /ui/v2/login/register/password
 *       [data-testid="password-text-input"]
 *       [data-testid="password-confirm-text-input"]
 *       [data-testid="submit-button"]          ("Continue")
 *
 *  3. submit                            → /ui/v2/login/verify?...&send=true
 *       Zitadel auto-sends the code email here. The verify page expects the CODE:
 *       [data-testid="code-text-input"]
 *       [data-testid="submit-button"]          ("Continue")
 *       [data-testid="resend-button"]
 *
 *  4. Read the code from Mailpit. Zitadel's email body carries the code both inline
 *     ("Code XXXXX") and inside the verify link's `?code=XXXXX&userId=...` query.
 *     IMPORTANT: visiting that full link directly is unreliable here — it carries a
 *     `requestId` and intermittently renders a "LOGIN ERROR" server-components page and
 *     does NOT verify the email. Entering the code into [data-testid="code-text-input"]
 *     on the verify page we are already on completes verification AND finalizes the OIDC
 *     auth request, redirecting back to {FRONTEND_URL} with the user logged in
 *     (litcal_access_token + litcal_id_token cookies set, email_verified=true).
 *
 *  5. submit                            → 302 back to {FRONTEND_URL}/... (authenticated)
 *
 * Stale-email gotcha: waitForVerificationLink returns as soon as ANY message to the
 * address has a verification link — so a leftover email from a previous run yields a
 * STALE code and verification fails with "Could not verify email". This driver therefore
 * purges Mailpit messages to the target address before starting, so only the fresh code
 * email matches.
 */

const MAILPIT_API_URL = (process.env.MAILPIT_API_URL || 'http://localhost:8025').replace(/\/$/, '');
const FRONTEND_URL = (process.env.FRONTEND_URL || 'http://localhost:3000').replace(/\/$/, '');

export interface RegistrationUser {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
}

interface MailpitListItem {
    ID: string;
    To?: Array<{ Address?: string }>;
}

/**
 * Delete any Mailpit messages already addressed to `email`, so the verification poll only
 * ever sees the code email generated by this registration attempt (avoids stale codes).
 */
async function purgeMailpitFor(email: string): Promise<void> {
    const res = await fetch(`${MAILPIT_API_URL}/api/v1/messages`);
    if (!res.ok) return;
    const list = (await res.json()) as { messages?: MailpitListItem[] };
    const target = email.toLowerCase();
    const ids = (list.messages || [])
        .filter((m) => (m.To || []).some((t) => (t.Address || '').toLowerCase() === target))
        .map((m) => m.ID);
    if (ids.length === 0) return;
    await fetch(`${MAILPIT_API_URL}/api/v1/messages`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ IDs: ids }),
    });
}

/**
 * Drive Zitadel's login-v2 self-registration UI for `user`, retrieve the verification code
 * Zitadel emails to Mailpit, complete verification, and leave the user logged in (the page
 * ends up back on {FRONTEND_URL} with the auth cookies set). The resulting account is a
 * verified, password-login-capable user in ZITADEL_ORG_ID — ready for oidcLogin /
 * actingAs once a scenario grants it whatever role/FGA it needs.
 *
 * Resolves once verification has fully completed; throws (via Playwright's auto-waiting
 * timeouts) if any step of the flow does not appear.
 */
export async function registerAndVerify(page: Page, user: RegistrationUser): Promise<void> {
    await purgeMailpitFor(user.email);

    // 0. Initiate login → Zitadel loginname page → open the registration form.
    await page.goto(`${FRONTEND_URL}/auth/login.php`);
    await Promise.all([
        page.waitForURL(/\/register(\?|$)/, { timeout: 20000 }),
        page.click('[data-testid="register-button"]'),
    ]);

    // 1. Profile + auth-method selection.
    await page.fill('[data-testid="firstname-text-input"]', user.firstName);
    await page.fill('[data-testid="lastname-text-input"]', user.lastName);
    await page.fill('[data-testid="email-text-input"]', user.email);
    await page.click('[data-testid="password-radio"]');
    await Promise.all([
        page.waitForURL(/\/register\/password/, { timeout: 20000 }),
        page.click('[data-testid="submit-button"]'),
    ]);

    // 2. Set the password.
    await page.fill('[data-testid="password-text-input"]', user.password);
    await page.fill('[data-testid="password-confirm-text-input"]', user.password);
    await Promise.all([
        page.waitForURL(/\/verify(\?|$)/, { timeout: 20000 }),
        page.click('[data-testid="submit-button"]'),
    ]);

    // 3. Pull the verification code Zitadel just emailed, and enter it.
    const link = await waitForVerificationLink(user.email, { timeoutMs: 30000 });
    const codeMatch = link.match(/[?&]code=([^&]+)/);
    if (!codeMatch) {
        throw new Error(`registerAndVerify: no code in verification link for ${user.email}: ${link}`);
    }
    const code = decodeURIComponent(codeMatch[1]);

    // 4. Submitting the code verifies the email AND finalizes the OIDC auth request,
    //    redirecting back to the frontend with the user authenticated.
    await page.fill('[data-testid="code-text-input"]', code);
    await Promise.all([
        page.waitForURL((u) => u.toString().startsWith(FRONTEND_URL), { timeout: 30000 }),
        page.click('[data-testid="submit-button"]'),
    ]);
}
